[build]
publish = "build/web"
command = "flutter build web --release"

[[plugins]]
package = "@netlify/plugin-inline-functions"

[[plugins]]
package = "@netlify/plugin-hash-files"
config = { "files" = ["build/web/main.dart.js"] }